#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
rm log.foamRun

cp -f system/fvSchemes.vanAlbada system/fvSchemes

runParallel foamRun
